config/routes.rb
Bookstash::Application.routes.draw do

  resources :books

  get   '/signin', :to => 'sessions#new', :as => :signin
  get   '/signout', :to => 'sessions#destroy', :as => :signout
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  root :to => 'pages#index'
end

app/models/authorization.rb
class Authorization
  include Mongoid::Document

  belongs_to :user

  field :provider, type: String
  field :uid, type: String

  validates :provider, :uid, presence: true
  validates_uniqueness_of :uid, scope: :provider

  class << self
    def build_from_authorization(auth_hash)
      Authorization.new(
        provider: auth_hash['provider'],
        uid: auth_hash['uid']
      )
    end

    def find_by_authorization(auth_hash)
      Authorization.where(
        provider: auth_hash["provider"],
        uid: auth_hash["uid"]
      ).first
    end
  end
end

app/models/book.rb
class Book
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :user

  field :title, type: String
  validates_presence_of :title
end

app/models/user.rb
class User
  include Mongoid::Document

  embeds_many :books

  has_many :authorizations, dependent: :destroy
  accepts_nested_attributes_for :authorizations

  field :name, type: String
  field :email, type: String

  before_validation :normalize_email

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def add_authorization(auth_params)
    new_auth = Authorization.build_from_authorization(auth_params)
    self.authorizations << new_auth
    new_auth
  end

  class << self
    def create_from_authorization(auth_params)
      email = auth_params['info']['email']
      user = User.where(email: email).first || User.new(email: email)
      user.name = auth_params['info']['name']
      user.authorizations << Authorization.build_from_authorization(auth_params)
      user.save!
      user
    end
  end

  protected
  def normalize_email
    self.email = email.strip.downcase if self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  protected

  def require_current_user
    unless current_user.present?
      flash[:alert] = 'Please sign in.'
      redirect_to signin_url
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      nil
    end
  end

  def current_user=(user)
    if user.nil?
      @current_user = session[:user_id] = nil
    else
      session[:user_id] = user.id
      @current_user = user
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :require_current_user

  def index
    @books = current_user.books
  end

  def create
    clean_params = params[:book].slice(:title)
    book = current_user.books.new(clean_params)
    if book.save
      render json: { title: book.title }, status: :ok
    else
      render json: { errors: book.errors.full_messages }, status: :bad_request
    end
  end

  def destroy
    book = current_user.books.find(params[:id])

    if book.destroy
      render json: { success: true }, status: :ok
    else
      render json: { success: false }, status: :bad_request
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]

  def new
  end

  def create
    auth_hash = request.env['omniauth.auth']

    if self.current_user
      Rails.logger.debug "** Already logged in: #{self.current_user.email}"
      self.current_user.add_authorization(auth_hash)
      redirect_to root_url
    else
      @authorization = Authorization.find_by_authorization(auth_hash)
      if @authorization
        self.current_user = @authorization.user
        Rails.logger.debug "** Found authorization: #{self.current_user.email}"
        redirect_to root_url
      else
        self.current_user = User.create_from_authorization(auth_hash)
        Rails.logger.debug "** Created user: #{self.current_user.email}"
        redirect_to root_url
      end
    end
  end

  def failure
  end

  def destroy
    self.current_user = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.haml
= form_for Book.new, remote: true do |f|
  = f.label :title
  = f.text_field :title
  = f.submit 'Add Book'

%ul{:id => 'book_list'}
  - @books.each do |book|
    %li
      = book.title
      = button_to "Delete", book_path(book),
        id: "delete-#{book.id}",
        form_class: 'delete-book',
        confirm: "Are you sure?",
        remote: true,
        method: :delete

app/views/books/index.html.slim
= form_for Book.new, remote: true do |f|
  = f.label :title
  = f.text_field :title
  = f.submit 'Add Book'

ul id='book_list'
  - @books.each do |book|
    li
      = book.title
      = button_to "Delete", book_path(book),
        id: "delete-#{book.id}",
        form_class: 'delete-book',
        confirm: "Are you sure?",
        remote: true,
        method: :delete

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Book Stash
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body id=(controller.controller_name) class=(controller.action_name)
    header.navbar
      div.navbar-inner
        div.container
          = link_to "Book Stash", root_path, class: 'brand'
          ul.nav
            li.active
              = link_to "Home", root_path
            li
              = link_to "Books", books_path
          ul.nav.pull-right
            - if current_user
              li
                ul.nav
                  li.dropdown
                    a.dropdown-toggle data-toggle='dropdown'
                      =' current_user.name
                      b.caret
                    ul.dropdown-menu
                      = link_to 'Sign Out', signout_path
            - else
              li
                = link_to 'Sign In', signin_path
    div.container
      - flash.each do |name, message|
        div class="alert alert-#{name}"
          = message
      = yield

app/views/pages/index.html.erb
<h1>Book Stash: <%= Rails.env %></h1>
<p>Your eBooks, organized and accessible.</p>